[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info

[INPUT]
    Name          systemd
    Tag           syslog
    Systemd_Filter _TRANSPORT=syslog
    Read_From_Tail On

[INPUT]
    Name          systemd
    Tag           auth
    Systemd_Filter _COMM=sshd
    Read_From_Tail On

[OUTPUT]
    Name          loki
    Match         *
    Host          127.0.0.1
    Port          3100
    Labels        job=fluentbit